### ISSUE TITLE
question

### ISSUE THREAD

**Issue by unclevito2017** [ilkerccom/bitcrackrandomiser#1]
it looks like the program creates a static start and end of the first 6 hex then the program does a sequential search of the range difference of one trillion , ninety nine billion +. when is the database created and where. Is it possible for the program to do this operation in a specific keyspace for example 30 or 29, or manually set checkpoints?

**Comment by ilkerccom** [comment]
Hi, yes it works as you mentioned. I keep the database on my own server. The program works with the API. You will see it when you examine the codes. The API simply returns a random HEX value and flags the scanned private key.

`Is it possible for the program to do this operation in a specific keyspace for example 30 or 29, or manually set checkpoints?`

Unfortunately, no.

**Comment by ilkerccom** [comment]
Closing issue. If you have any further questions, please open a new issue.
