### ISSUE TITLE
Server owner can identify the range containing the puzzle key!

### ISSUE THREAD

**Issue by oshimoto** [ilkerccom/bitcrackrandomiser#11]
Hi! The code as its is would allow the server owner to identify the range which found the puzzle private key and potentially withdraw it before the lucky finder.

The server keeps the average time to return a task per GPU, so a task returned faster would indicate it has found the puzzle private key.
The server owner could have a script running to detect task returned faster than usual, scan the range and swipe the puzzle address.

One way that comes to mind to fix this is to add code to client side program to create the address for the last key in the range to be scanned and include that address in the call to BitCrack.
That way BitCrack will finish the task ONLY after the whole range has been scanned.

I think that would be fair and square for all.

**Comment by oshimoto** [comment]
Ok let me check the code again and make sure when puzzle key is found the range is not send to server to be flagged as scanned.
Thanks for your reply!

**Comment by ilkerccom** [comment]
Added 'force_continue' feature 4a5efab

`true` If the private key is found, the scan will continue until it is finished. The related range is marked as "scanned". The key found is publicly visible on the pool site. (With 1 missing character)

You can see the private key in the file created in the folder and if Telegram is active, notification will come.

`false` If the private key is found, the scanning process is terminated. No data is sent to the pool.
