### ISSUE TITLE
Token mandatory?

### ISSUE THREAD

**Issue by Flydancer** [ilkerccom/bitcrackrandomiser#15]
Hi, is it mandatory to use a token now or is it still possible to join the pool anonymously? I'm always getting a Database Error since your last update

**Comment by ilkerccom** [comment]
Hello,

Please update to latest version. The "User Token" value is currently not mandatory.

I have integrated a payment system for those who join the pool later. It will be mandatory to use the "user token" value when payment is active.

And remember, you are always anonymous on the pool.
