### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by fahimaltinordu** [ilkerccom/bitcrackrandomiser#18]
Hello, 
i am getting an error as 'out of memory' but i dont know why, do you have any idea?

![IMG_20230908_205757](https://github.com/ilkerccom/bitcrackrandomiser/assets/58973431/1f512ec6-f5e0-4586-b704-3809a9a0cd3f)

**Comment by ilkerccom** [comment]
I answered this issue on Telegram group.

Error about "app_arguments". Leave blank or enter right values for your GPU.

Thanks.
