### ISSUE TITLE
Flag error

### ISSUE THREAD

**Issue by RealXIII** [ilkerccom/bitcrackrandomiser#19]
![image](https://github.com/ilkerccom/bitcrackrandomiser/assets/144704748/f11b1d4e-3bc1-47b2-968f-627ca49e0165)

Hello, I end up with this error when I launch the application, can you help me?

**Comment by ilkerccom** [comment]
Answered on Telegram.

Use v0.30 version of bitcrack app for AMD/OpenCL.

Thanks.
