### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by sari777** [ilkerccom/bitcrackrandomiser#2]
can you please tell what is the full command without cuda.? i am writing as "BitcrackRandomiser.exe -b 256 -t 256 -p 512 --keyspace 2c816a70000000000:2c816a80000000000 13zb1hQbWVsc2S7ZTZnP2G4undNNpdh5so"
this is the basic setting for my pc with bitcrack..not yours "-b 256 -t 256 -p 512 "..the bitcrack runs perfectly on these settings.
your program is giving error.
"Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at BitcrackRandomiser.Helpers.GetSettings(Int32 Line) in C:\Users\ilker\source\repos\BitcrackRandomiser\BitcrackRandomiser\Helpers.cs:line 32
   at BitcrackRandomiser.Program.RunBitcrack() in C:\Users\ilker\source\repos\BitcrackRandomiser\BitcrackRandomiser\Program.cs:line 50
   at BitcrackRandomiser.Program.Main(String[] args) in C:\Users\ilker\source\repos\BitcrackRandomiser\BitcrackRandomiser\Program.cs:line 20"

or it is on;y for cuda devices.?

**Comment by ilkerccom** [comment]
Hello, 

Please share your OS. Windows or Linux?

**Comment by sari777** [comment]
i have windows system. and here is the settings in settings.txt file. i just removed your wallet addrress. remaining untouched. "-b 896 -t 256 -p 256 -o {2}.txt --keyspace {0}0000000000:{1}0000000000 {2}"

**Comment by ilkerccom** [comment]
Thanks for feedback. **You must fill** "wallet address line". You can enter your BTC address or any other nick name. My guess is, your BTC wallet address.

**Comment by sari777** [comment]
> Hello,
> 
> Please share your OS. Windows or Linux? And please settings.txt content.
> 
> You must write Bitcrack arguments in settings.txt file. Then start "bitcrackrandomiser.exe".
> 
> Example settings.txt
> 
> `C:\{bitcrackfolder}\cuBitCrack.exe` `-b 896 -t 256 -p 256 -o {2}.txt --keyspace {0}0000000000:{1}0000000000 {2}` `{yourwalletaddress}`
> 
> You can edit arguments `-b 896 -t 256 -p 256` . Example; `-b 256` or `empty`
> 
> You can't change this arguments: `-o {2}.txt --keyspace {0}0000000000:{1}0000000000 {2}`
> 
> Thanks.

ok dear. let me check. thanks for quick response.
and tell me one thing. it requires internet for run. if by luck the private key hit, then the amount of the wallet address of 66 puzzle  will be share to your personal wallet address directly.? i am confused. is it safe.?

**Comment by ilkerccom** [comment]
Thanks. This app is open-source. You can review the codes.

**_An extra suggestion is for Bitcrack app: Compile and build it for yourself._** Because Bitcrack app will find the private key. BitcrackRandomiser is a work distribution system (like pool) that works simultaneously with Bitcrack.

This app using internet for getting new HEX values and updating HEX values. (With API). 

Please review the `Requests.cs` file. Here you can see what data is sent to the API.

**Comment by sari777** [comment]
ok dear.thanks for all help.

**Comment by ilkerccom** [comment]
I am closing issue. If you have any further questions, please open a new issue.
