### ISSUE TITLE
Can't run all available GPUs

### ISSUE THREAD

**Issue by AsicPrince** [ilkerccom/bitcrackrandomiser#23]
I follow the instruction but your tool only run 1 of my 3pgus. what is wrong here? and with vanbitcrack speed can run all 3 gpus, reach 1500Mkeys/s/gpu with my 3070ti but use bitcrack only reach 1200Mkey, let combine with vanbitcrack to improve the speed.

// Select puzzle number [66,67,68] or [38] for test pool
target_puzzle=66

// which app will be used [bitcrack]
app_type=bitcrack

// App folder path [cuBitcrack, clBitcrack or full path of the Bitcrack app]
app_path=cuBitcrack

// App arguments
// Example for bitcrack: -b 896 -t 256 -p 256
app_arguments=-b 896 -t 256 -p 256

// Enter your GPU Count [1-32]
gpu_count=3

**Comment by ilkerccom** [comment]
Hi,

When the application works with multiple graphics cards, it only shows the information of a single graphics card. (On console)

I will update for this, but I have not free time yet.

I looked at the application you mentioned, but it is not open source. So it doesn't make sense.

**Comment by AsicPrince** [comment]
no my friend, only 1 GPU work, i can see it by watch their fans working or not

**Comment by ilkerccom** [comment]
Possibly the cards may be giving errors, I will make an update for this, I added it to my to-do list for now.

In order to see the error better; Please send me a private message on Telegram. I can connect with AnyDesk and see the error in detail.

**Comment by ilkerccom** [comment]
Repo updated for this problem.
