### ISSUE TITLE
Source code of the DLLs used by BitcrackRandomiser

### ISSUE THREAD

**Issue by crisdeb** [ilkerccom/bitcrackrandomiser#25]
In the source code of **BitcrackRandomiser**, compared to "_releases_" there is no trace of the source code of the DLLs needed by the program viz: **Telegram.Bot.dll** and **Newtonsoft.Json.dll**.
Can you provide the source code or all references to verify that they are **legitimate**?
Thank you

**Comment by ilkerccom** [comment]
These packages are packages included in the application via nuget. You can find open source codes on github.
