### ISSUE TITLE
telegram_share_eachkey=false ignored

### ISSUE THREAD

**Issue by krishnathon2006** [ilkerccom/bitcrackrandomiser#30]
Starting version 1.2.0.0, `telegram_share_eachkey=false` settings is ignored and my Telegram channel filled with "scanned by" messages from my worker.

**Comment by krishnathon2006** [comment]
I've checked 1.0.8.0 and confirmed that `telegram_share_eachkey=false` setting is respected there. 
As expected, I receive "started job for" at the start of the app, but don't receive notifications for each key scan

**Comment by ilkerccom** [comment]
I will fix the problem in the next version; If you want to solve it quickly, you can make the following change and get a new build;

https://github.com/ilkerccom/bitcrackrandomiser/blame/main/BitcrackRandomiser/Randomiser.cs#L227

It will be enough to put this code in the "if" block;

```C
if (settings.TelegramShareEachKey)
{
    Helpers.ShareTelegram(string.Format("[{0}] scanned by [{1}].[{2}]", HEX, Helpers.StringParser(settings.ParsedWalletAddress), settings.ParsedWorkerName), settings);
}
```

Working example on 1.8v;
https://github.com/ilkerccom/bitcrackrandomiser/blame/v1.0.8.0/BitcrackRandomiser/Program.cs#L258-L261

**Comment by ilkerccom** [comment]
Fixed. ff97dcc
