### ISSUE TITLE
Speed question

### ISSUE THREAD

**Issue by allinbit** [ilkerccom/bitcrackrandomiser#31]
This program using bitcrack, which performance is not the best.

A 4090 using the vanitysearch with bitcrack option will gets 5000 MKey/s, and using KeyHuntCuda will gets over 6000 MKey/s.

But bitcrack only gets 3000 Mkey/s, can you upgrade this program using other tools to archive higher speed?

**Comment by ilkerccom** [comment]
Hello, yes I know. I wanted to integrate Keyhunt-Cuda, but unfortunately there are many problems with multi-address scanning and it cannot find the addresses.

VanitySearch is a good alternative, but it doesn't support custom range scanning and I don't think it does multi-address scanning.

If you find good open source alternatives, please let me know and I will integrate them with great pleasure.

Thanks.

**Comment by allinbit** [comment]
You can see my uploaded version of vanitysearch: [](https://github.com/allinbit/VanitySearch)

**Comment by ilkerccom** [comment]
Thanks, it looks great. I will test this.

**Comment by ilkerccom** [comment]
Updated. ff97dcc

Thanks for your share.

**Comment by allinbit** [comment]
Thank you for your working! @ilkerccom 

I tried run app in vanitysearch mode, but it seems missing _vanitysearch.txt_ file. `[ERROR] ParseFile: cannot open vanitysearch.txt No such file or directory`

How should I edit `app_arguments` parameter in setting file? I think it should put the addresses that will be scanned in each range into the _vanitysearch.txt_ file and then specify the output file with the `-o` operation.

Thanks!

**Comment by WanderingPhilosopher** [comment]
What do you mean there were problems finding address with keyhunt-cuda? Can you explain better? And did you get the vanitysearch to work?

**Comment by ilkerccom** [comment]
> Thank you for your working! @ilkerccom
> 
> I tried run app in vanitysearch mode, but it seems missing _vanitysearch.txt_ file. `[ERROR] ParseFile: cannot open vanitysearch.txt No such file or directory` Tested in ubuntu20.04.
> 
> How should I edit `app_arguments` parameter in setting file? I think it should put the addresses that will be scanned in each range into the _vanitysearch.txt_ file and then specify the output file with the `-o` operation.
> 
> Thanks!

I tested it many times on Linux and Windows and I did not receive such an error. The specified file is created with each scan and contains the addresses to be scanned.

Do not use the -o parameter in arguments. Because I need to read the keys from the console for the proof of work system to work. I think I turned this off in Vanitysearch, which I had already forked. Apart from that, you can use other arguments.

> What do you mean there were problems finding address with keyhunt-cuda? Can you explain better? And did you get the vanitysearch to work?

I want Keyhunt-Cuda to find 3 addresses, but most of the time it doesn't. It works flawlessly in single address scanning. However, unfortunately, it cannot find the addresses you want in multi-address scanning.

**Comment by allinbit** [comment]
A new problem appeared.

```
Unhandled exception. System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/root/BitCrack/bitcrackrandomiser/BitcrackRandomiser/bin/Debug/net6.0/vanitysearch/./vanitysearch' with working directory '/root/BitCrack/bitcrackrandomiser/BitcrackRandomiser'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at BitcrackRandomiser.Randomiser.Scan(Settings settings, Int32 gpuIndex) in /root/BitCrack/bitcrackrandomiser/BitcrackRandomiser/Randomiser.cs:line 224
   at BitcrackRandomiser.Program.Main(String[] args) in /root/BitCrack/bitcrackrandomiser/BitcrackRandomiser/Program.cs:line 51
```

ubuntu 20.04 cuda 12.2
And my parameter are
```
// which app will be used [bitcrack,vanitysearch,cpu]
app_type=vanitysearch

// App folder path
// [cuBitcrack, clBitcrack or full path of the Bitcrack app]
// [vanitysearch or full path of the Vanitysearch app]
// [vanitysearch for CPU support]
app_path=vanitysearch

// App arguments
// Example for bitcrack: -b 896 -t 256 -p 256
app_arguments=
```

**Comment by ilkerccom** [comment]
> `I want Keyhunt-Cuda to find 3 addresses, but most of the time it doesn't. It works flawlessly in single address scanning. However, unfortunately, it cannot find the addresses you want in multi-address scanning.`
> 
> Did you try it by doing the correct conversions? Multi address = convert to h160 to binary and then sort the results before running? Can one use it via app_path=/app/VanitySearch/./vanitysearch but change to keyhunt-cuda?
> 
> I know it works if ran properly. The vanitysearch should run correctly as well, depending on which version one is using.

Yes, I followed all the steps, but I could not manage to scan multiple addresses. If you help, I can also integrate "keyhunt-cuda". 

Thanks.

**Comment by WanderingPhilosopher** [comment]
I would need you to setup a random 40 bit range, and provide me 3 addresses which lie in the range. You run it and I run it and we will share results of keys found. Share settings, etc. so we can compare.

**Comment by ilkerccom** [comment]
> I would need you to setup a random 40 bit range, and provide me 3 addresses which lie in the range. You run it and I run it and we will share results of keys found. Share settings, etc. so we can compare.

Thanks, I'll need some time for this. If you wish, you can also write to me on telegram.
