### ISSUE TITLE
good luck, bad luck

### ISSUE THREAD

**Issue by HumSaw** [ilkerccom/bitcrackrandomiser#35]
Hello. By searching the site, a solution to problem 67 appeared. Out of excitement, I accidentally reloaded the page and the window with the required private key disappeared. This happened about 10-15 minutes ago. I hope the site saves the solution somewhere. It definitely showed up. Check, please. I'm waiting for your answer!

**Comment by ilkerccom** [comment]
Hello are you talking about the website? If so, your chances of finding 67 through a browser are unfortunately close to impossible.

Apart from that, the website works client-based and unfortunately we cannot see the scanned keys.

**Comment by HumSaw** [comment]
Yes, I'm talking about the website. I know that the chances are slim, I launched it from my phone, the search began, I clicked return to the previous page and at that moment a square window appeared, where the private key, public key and some other information were indicated. Upon return, the information was reset and other private keys were generated.

**Comment by ilkerccom** [comment]
I'm sorry, but the generated keys are created on the client browser.
