### ISSUE TITLE
Does not work with Nvidia HM100 chips

### ISSUE THREAD

**Issue by gitconsumer** [ilkerccom/bitcrackrandomiser#39]
I've tried to run the docker container on a server with HM100 and it doesn't work displaying an error message:

"Error names symbol not found GPU 0".

4090 RTX works fine.

**Comment by ilkerccom** [comment]
Hello, I rented many H100s and tried different CCAP values (both bitcrack and vanitysearch), and I got the error you mentioned in all of them. I'll let you know if I learn anything new.

**Comment by thewhitegrizzli** [comment]
try chatGPT maybe
Laurent
