### ISSUE TITLE
hi dear

### ISSUE THREAD

**Issue by sari777** [ilkerccom/bitcrackrandomiser#4]
dear can you please guide me how to use these gpu..sss. not understanding anything. "sarletaadams@gmail.com". how to proceed after opening "https://cloud.vast.ai/"
'

**Comment by ilkerccom** [comment]
Hello,

You can follow similar video on [Youtube](https://www.youtube.com/watch?v=1BHNer9dZ_M)

Thanks.

**Comment by sari777** [comment]
hey thanks for reply but in this video, the guy did not tell about how to include gpu for ssh. and where to put commands.

**Comment by ilkerccom** [comment]
Hello,

The first 10 minutes of the Youtube video show what you need to do. Then you can follow the commands in the README.md file.

**Comment by sari777** [comment]
ok dear.
