### ISSUE TITLE
Cloud search problem.

### ISSUE THREAD

**Issue by a8832021** [ilkerccom/bitcrackrandomiser#40]
Hello. I've already create a cloud search instance. But it stayed at "Wait while the instance is initializing...Downloaded..." status for a long time and I can find "Error response from daemon: No such container: C.10611154" in the log. I didn't enter a ssh key. What's wrong?  And how can I make sure that if the key is finded, it won't be stolen by the compute power provider? How can I find the key in the remote machine?
Thanks for helping me.

**Comment by ilkerccom** [comment]
Hello, errors may occur in some of the instances (especially some of the cheaper ones).

If you have activated API share or Telegram sharing, you will be notified when the key is found. If you have run an instance with default settings, you can see it in the "logs" section if the key is found. My advice is to at least set up a sharing mechanism.

If you set the "untrusted computer" setting to off, the found key will not be saved in the running instance. However, for this you need to activate at least the API Share or Telegram Share feature.

Thanks.

**Comment by ilkerccom** [comment]
I'm closing the issue, if you have any questions, feel free to write.
