### ISSUE TITLE
A problem about billing of cloud search.

### ISSUE THREAD

**Issue by a8832021** [ilkerccom/bitcrackrandomiser#41]
In the cloud search instance page, the total fees per hour is less than the sum of all the fees of instances.However, the balance decrease rate seems to be faster than the sum of all the fees. What's wrong?Are there any other hidden fees in the service?
Thanks for helping me.

**Comment by ilkerccom** [comment]
Hello, there is no hidden fee. The amount spent should be the same as the fees shown. Can I know your username so I can check it?

Thanks.

**Comment by ilkerccom** [comment]
> In the cloud search instance page, the total fees per hour is less than the sum of all the fees of instances.However, the balance decrease rate seems to be faster than the sum of all the fees. What's wrong?Are there any other hidden fees in the service? Thanks for helping me.

Hello again. Now when I looked at my own account, I saw the same problem. Total cost calculation is done incorrectly. Now I solved the problem. Thank you for feedback.
