### ISSUE TITLE
Cloud search cost.

### ISSUE THREAD

**Issue by a8832021** [ilkerccom/bitcrackrandomiser#42]
I found that the balance decreasing speed is a little faster than the instances price rate. I opened a instance which price is 0.1$/hr.And after 35 hours, my balance decreased 3.8$. Is there any bugs?

**Comment by ilkerccom** [comment]
Hello, I will look into this issue.

**Comment by ilkerccom** [comment]
Hello again, 

I have been testing for a long time, I haven't encountered any problems yet. Can you please indicate whether the problem persists or not?

**Comment by ilkerccom** [comment]
I'm closing the issue, if you see a problem again you can reply.
