### ISSUE TITLE
ARM CPU support?

### ISSUE THREAD

**Issue by auc0le** [ilkerccom/bitcrackrandomiser#43]
Is there anyway to run this on Apple ARM (M1) in CPU mode?

How about on other ARM CPU's like raspberry pi?

Thanks

**Comment by ilkerccom** [comment]
Hello, 

I didn't test it. Even if the app works, i'm not so sure "VanitySearch" will work. Have you tried it? Are you getting any errors?

Thanks.

**Comment by auc0le** [comment]
After a review of the VanitySearch code, it appears that they are using intrinsic assembly commands (aka Intel Intrinsics) that are AMD64 specific to optimize performance.   Thus the code isn't compatible with an ARM processor - at least in the current code base. 

:(

**Comment by ilkerccom** [comment]
The CPU is already quite slow for puzzles. It would be a more logical move to use [Vast.ai](https://cloud.vast.ai/?ref_id=69296) or [Cloud Search](https://btcpuzzle.info/cloud-search) instead. Or that way if you have your own GPU.

If you just want to experiment, I think there are a few programs that run on the CPU. I also have a [.NET Core based program](https://github.com/ilkerccom/bitcoinpuzzlescanner) that I wrote to experience before. But remember, it is much slower than other programs and I don't recommend it.
