### ISSUE TITLE
Documentation for untrusted_computer is mismatched

### ISSUE THREAD

**Issue by kuopassa** [ilkerccom/bitcrackrandomiser#5]
Please confirm the correct meaning of these settings:

untrusted_computer=true
untrusted_computer=false

In the documentation there are 2 descriptions for them, but they are describing the opposite result.

**Comment by ilkerccom** [comment]
Hello, sorry for mismatch. I updated it. 

untrusted_computer=false 
If the private key is found, it will appear on the console screen. Also, a new text file will be created in the folder where the application is run. (in the name of the target wallet address.)

untrusted_computer=true 
If the private key is found, it will send your Telegram channel/group only.

**Comment by ilkerccom** [comment]
I'm closing the issue. If there is any other issue, please feel free to open a new issue.
