### ISSUE TITLE
Error Statistic

### ISSUE THREAD

**Issue by 0xHenz** [ilkerccom/bitcrackrandomiser#55]
Hello,

I joined Puzzle 69 pool, running 4 hours straight but my account statistic still 0 scanned.
Also theres showing 0 active worker.
My btcpuzzle account is henzcorp.
How to fix it? Can you check it, please?

Thanks!

**Comment by ilkerccom** [comment]
Hello, please send your "username" and "settings file". You can use Telegram or support@btcpuzzle.info.

I will check it. Thanks.
